### ISSUE TITLE
Comparison to YahooFinanceApi

### ISSUE THREAD

**Issue by dotnetshadow** [dshe/YahooQuotesApi#7]
Hi there,

Firstly, great work on this project. 
Is this an enhancement of https://github.com/karlwancl/YahooFinanceApi?

Questions:
1. I noticed you did updates on the original project, Just wondering, is there a comparison or is the api similar to the other one? 
2. Is there a way to specify only required fields for a security i.e. only grab the price and not other fields like longName etc? This could help with the amount of data being downloaded?
3. Can this do as much as the other project?

I'm thinking of migrating to this project, since it has recently been updated, just wanting to know your thoughts thanks

**Comment by dshe** [comment]
I had made so many changes to [karlwancl/YahooFinanceApi](https://github.com/karlwancl/YahooFinanceApi?) that I decided to create an independent project. The [dshe/YahooQuotesApi](https://github.com/dshe/YahooQuotesApi) project improves and extends the functionality of the original project. For example, it supports caching, fault-tolerance, and currency conversion.

Yes, the download size would decrease if only the necessary fields were retrieved. But the amount of data is small even when including all fields. Results are cached so that subsequent requests for any field will not require another download.

Thank you for your interest!
